# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'my_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10my_service.proto\"\x1c\n\nBidRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\".\n\x0b\x42idResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x32\x34\n\tOrderBook\x12\'\n\nGetBestBid\x12\x0b.BidRequest\x1a\x0c.BidResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIDREQUEST']._serialized_start=20
  _globals['_BIDREQUEST']._serialized_end=48
  _globals['_BIDRESPONSE']._serialized_start=50
  _globals['_BIDRESPONSE']._serialized_end=96
  _globals['_ORDERBOOK']._serialized_start=98
  _globals['_ORDERBOOK']._serialized_end=150
# @@protoc_insertion_point(module_scope)
