# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import my_service_pb2 as my__service__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in my_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOrder = channel.unary_unary(
                '/OrderBookService/AddOrder',
                request_serializer=my__service__pb2.OrderRequest.SerializeToString,
                response_deserializer=my__service__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetBestBid = channel.unary_unary(
                '/OrderBookService/GetBestBid',
                request_serializer=my__service__pb2.Empty.SerializeToString,
                response_deserializer=my__service__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetBestAsk = channel.unary_unary(
                '/OrderBookService/GetBestAsk',
                request_serializer=my__service__pb2.Empty.SerializeToString,
                response_deserializer=my__service__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/OrderBookService/GetOrderBook',
                request_serializer=my__service__pb2.Empty.SerializeToString,
                response_deserializer=my__service__pb2.OrderBookResponse.FromString,
                _registered_method=True)
        self.GetTradeLog = channel.unary_stream(
                '/OrderBookService/GetTradeLog',
                request_serializer=my__service__pb2.Empty.SerializeToString,
                response_deserializer=my__service__pb2.Trade.FromString,
                _registered_method=True)


class OrderBookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestBid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestAsk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrder,
                    request_deserializer=my__service__pb2.OrderRequest.FromString,
                    response_serializer=my__service__pb2.OrderResponse.SerializeToString,
            ),
            'GetBestBid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestBid,
                    request_deserializer=my__service__pb2.Empty.FromString,
                    response_serializer=my__service__pb2.OrderResponse.SerializeToString,
            ),
            'GetBestAsk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestAsk,
                    request_deserializer=my__service__pb2.Empty.FromString,
                    response_serializer=my__service__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=my__service__pb2.Empty.FromString,
                    response_serializer=my__service__pb2.OrderBookResponse.SerializeToString,
            ),
            'GetTradeLog': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTradeLog,
                    request_deserializer=my__service__pb2.Empty.FromString,
                    response_serializer=my__service__pb2.Trade.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OrderBookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderBookService/AddOrder',
            my__service__pb2.OrderRequest.SerializeToString,
            my__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderBookService/GetBestBid',
            my__service__pb2.Empty.SerializeToString,
            my__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderBookService/GetBestAsk',
            my__service__pb2.Empty.SerializeToString,
            my__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderBookService/GetOrderBook',
            my__service__pb2.Empty.SerializeToString,
            my__service__pb2.OrderBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/OrderBookService/GetTradeLog',
            my__service__pb2.Empty.SerializeToString,
            my__service__pb2.Trade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
